
on:
  push:
    branches:
      - feature/tomcatdeploy
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the artifacts
      run: |
        mvn -f pom.xml -B clean package
    - name: Publish the artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifacts
        path: "${{ github.workspace }}/target/*.war" 
    - name: Push to another repository
      uses: peter-evans/create-pull-request@v3
    - name: publish service
      run: mvn -f pom.xml release:prepare
    - name: Configure Git user
      run: |
          git config --global user.email "anushamadhala678@gmail.com"
          git config --global user.name "anushamadhala678"
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Build artifacts"
        files: /sysfoobuildfiles/target/*
        branch: build-artifacts
        base: feature/tomcatdeploy
        repository: anushamadhala678/practicegit

  



